---
- name : Configuration of nginx webserver with TLS  
  hosts: webserver
  become: True 
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/default
    server_name: localhost

  tasks:
    - name: Install nginx webserver
      yum: name=nginx state=latest
    
    - name: Create directories for certificate files
      file: path=/etc/nginx/ssl state=directory
   
    - name: Copy TLS key
      copy: src=files/nginx.key dest={{ key_file }} owner=root mode=0600
      notify: Restart nginx

    - name: Copy TLS certificate
      copy: src=files/nginx.crt dest={{ cert_file }}
      notify: Restart nginx

    - name: Copy nginx configuration file
      template: src=templates/nginx.conf.j2 dest={{ conf_file }}
      notify: Restart nginx

    - name: Copy index.html template
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644
  
  handlers:
    - name: Restart nginx
      service: name=nginx state=restarted


