---
- name: Configure webserver with nginx 
  hosts: webserver
  become: true
  tasks: 
  - name: install nginx
    yum: name=nginx  
 
  - name: Copy nginx configuration files
    copy: src=files/nginx.conf dest=/etc/nginx/conf.d/default 

  - name: copy index.html
    template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html
      mode=0644

  - name: restart nginx
    service: name=nginx state=restarted
