---

  - name: show return value of command module
    hosts: prepare
    tasks:
      - name: capture output of id command
        command: id -un
        register: login
      - debug: var=login
      - debug: msg="Login user is {{ login.stdout }}"

