---
 - name: This Playbook will prepare ansible host 
   hosts: prepare
   become: True
   tasks:
     - name: Remove user "user"
       user:
         name: user
         state: absent
         remove: yes 

