---
- name: Http installation and configuration (centos)
  hosts: webserver
  become: True
  gather_facts: false
  tasks:
    - name: Install apache(httpd) package.
      package: name=httpd state=present
      
    - name: Start apache(httpd) service 
      service: name=httpd state=started
      
